# Generated by Django 5.1.7 on 2025-10-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='!default_hash', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='!default_hash', max_length=128),
        ),
    ]
